//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLI.SRS2.Modules.Disclosure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLI.SRS2.Modules.Disclosure.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS.
        /// </summary>
        public static string DisclosureMaterial_Cas {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Cas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoE.
        /// </summary>
        public static string DisclosureMaterial_Coe {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Coe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_Nbr.
        /// </summary>
        public static string DisclosureMaterial_Enbr {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Enbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEMA.
        /// </summary>
        public static string DisclosureMaterial_Fema {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Fema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashpoint temperature.
        /// </summary>
        public static string DisclosureMaterial_FlashpointTemperature {
            get {
                return ResourceManager.GetString("DisclosureMaterial_FlashpointTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string DisclosureMaterial_Functions {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History status.
        /// </summary>
        public static string DisclosureMaterial_HistoryStatus {
            get {
                return ResourceManager.GetString("DisclosureMaterial_HistoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DisclosureMaterial_Id {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string DisclosureMaterial_Incomplete {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material group.
        /// </summary>
        public static string DisclosureMaterial_MaterialGroup {
            get {
                return ResourceManager.GetString("DisclosureMaterial_MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisclosureMaterial_Name {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string DisclosureMaterial_Percentage {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received on.
        /// </summary>
        public static string DisclosureMaterial_ReceivedOn {
            get {
                return ResourceManager.GetString("DisclosureMaterial_ReceivedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier short name.
        /// </summary>
        public static string DisclosureMaterial_SupplierShortName {
            get {
                return ResourceManager.GetString("DisclosureMaterial_SupplierShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPD2 Relevant.
        /// </summary>
        public static string DisclosureMaterial_Tpd2Relevant {
            get {
                return ResourceManager.GetString("DisclosureMaterial_Tpd2Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string DisclosureMaterial_ValidFrom {
            get {
                return ResourceManager.GetString("DisclosureMaterial_ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to.
        /// </summary>
        public static string DisclosureMaterial_ValidTo {
            get {
                return ResourceManager.GetString("DisclosureMaterial_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Disclosure Data.
        /// </summary>
        public static string DisclosureView_basicData {
            get {
                return ResourceManager.GetString("DisclosureView_basicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string DisclosureView_materials {
            get {
                return ResourceManager.GetString("DisclosureView_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclosure.
        /// </summary>
        public static string DisclosureView_Title {
            get {
                return ResourceManager.GetString("DisclosureView_Title", resourceCulture);
            }
        }
    }
}
